# Generated by Django 6.0.8 on 2026-08-17 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_module', '0001_initial'),
        ('candidates', '0001_initial'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=30, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_record', to='candidates.candidate')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='admin_module.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ID_PROOF', 'ID Proof'), ('TENTH_CERTIFICATE', '10th Certificate'), ('TENTH_MARKLIST', '10th Marklist'), ('TWELFTH_CERTIFICATE', '12th Certificate'), ('TWELFTH_MARKLIST', '12th Marklist'), ('EXPERIENCE_CERTIFICATE', 'Experience Certificate'), ('OTHER', 'Other')], max_length=50)),
                ('document', models.FileField(upload_to='employees/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('performance_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_period', models.CharField(max_length=50)),
                ('rating', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('AVERAGE', 'Average'), ('NEEDS_IMPROVEMENT', 'Needs Improvement')], max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('review_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_performance_reviews', to='hr.hrmanager')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('work_summary', models.TextField()),
                ('tasks_completed', models.TextField()),
                ('achievements', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('REVIEWED', 'Reviewed'), ('NEEDS_CORRECTION', 'Needs Correction')], default='SUBMITTED', max_length=30)),
                ('hr_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_employee_reports', to='hr.hrmanager')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceWarning',
            fields=[
                ('warning_id', models.AutoField(primary_key=True, serialize=False)),
                ('warning_date', models.DateField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('hr_recommendation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SENT_TO_ADMIN', 'Sent to Admin'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('admin_decision', models.CharField(blank=True, choices=[('CONTINUE', 'Continue Employment'), ('ANOTHER_WARNING', 'Another Warning'), ('TERMINATION', 'Termination')], max_length=30, null=True)),
                ('admin_comments', models.TextField(blank=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_warning_decisions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_warnings', to='employees.employee')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_warnings', to='hr.hrmanager')),
                ('performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='employees.employeeperformance')),
            ],
        ),
    ]
