# Generated by Django 5.2.7 on 2026-09-04 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/profile_photos/'),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='score',
            field=models.DecimalField(decimal_places=1, default=4.3, max_digits=3),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='title',
            field=models.CharField(default='Weekly Work Report', max_length=200),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('REPORT_REMINDER', 'Weekly Report Reminder'), ('HR_FEEDBACK', 'HR Feedback'), ('WARNING', 'Performance Warning'), ('ANNOUNCEMENT', 'Company Announcement'), ('PROFILE_UPDATE', 'Profile Update')], default='REPORT_REMINDER', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employees.employee')),
            ],
        ),
    ]
