# Generated by Django 6.0 on 2026-09-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_alter_employee_user_alter_hrmanager_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('HOLIDAY', 'Holiday'), ('NOTICE', 'Notice'), ('HR', 'HR Notice')], default='GENERAL', max_length=20, verbose_name='Announcement Type'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is Published'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published At'),
        ),
    ]
