# Generated by Django 6.0.8 on 2026-09-05 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('vacancy_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('department_name', models.CharField(help_text='Designated department name for the position', max_length=100)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship')], default='FULL_TIME', max_length=20)),
                ('experience_required', models.CharField(help_text='e.g., 2+ years, Entry Level', max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='Key skills and qualifications required')),
                ('openings_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to='hr.hrmanager')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
