# Generated by Django 6.0.8 on 2026-09-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('hr', '0002_jobvacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aptitudequestion',
            options={'ordering': ['category', '-created_at', 'question_id']},
        ),
        migrations.AddField(
            model_name='aptitudequestion',
            name='category',
            field=models.CharField(choices=[('QUANTITATIVE', 'Quantitative Aptitude'), ('LOGICAL', 'Logical Reasoning'), ('VERBAL', 'Verbal Ability')], default='QUANTITATIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='aptitudequestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='aptitudequestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aptituderesult',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aptituderesult',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aptitudetest',
            name='pass_percentage',
            field=models.PositiveIntegerField(default=50, help_text='Passing percentage required'),
        ),
        migrations.AddField(
            model_name='aptitudetest',
            name='total_questions',
            field=models.PositiveIntegerField(default=15, help_text='Number of questions presented to candidates across categories'),
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='correct_answer',
            field=models.CharField(help_text='Choice letter: A, B, C, or D', max_length=1),
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hr.aptitudetest'),
        ),
        migrations.AlterField(
            model_name='aptitudetest',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Duration of the test in minutes'),
        ),
        migrations.CreateModel(
            name='AptitudeAttempt',
            fields=[
                ('attempt_id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('questions_data', models.JSONField(default=list, help_text='Randomized question and shuffled option snapshot for this attempt')),
                ('answers_data', models.JSONField(default=dict, help_text='Candidate submitted answers mapping {question_id: selected_key}')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_attempts', to='candidates.jobapplication')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='hr.aptitudetest')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
