# Generated by Django 6.0.8 on 2026-09-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(default='All', max_length=50),
        ),
    ]
