# Generated by Django 6.0.8 on 2026-09-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0003_announcement_is_active_announcement_target_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('holiday_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('PUBLIC', 'Public Holiday'), ('RESTRICTED', 'Restricted Holiday'), ('COMPANY', 'Company Holiday')], default='PUBLIC', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
