# Generated by Django 6.0.8 on 2026-08-17 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='candidates/profile_photos/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='candidates/resumes/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='candidates/documents/')),
                ('tenth_certificate', models.FileField(blank=True, null=True, upload_to='candidates/documents/')),
                ('twelfth_certificate', models.FileField(blank=True, null=True, upload_to='candidates/documents/')),
                ('tenth_marklist', models.FileField(blank=True, null=True, upload_to='candidates/documents/')),
                ('twelfth_marklist', models.FileField(blank=True, null=True, upload_to='candidates/documents/')),
                ('policy_agreement', models.BooleanField(default=False)),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('vacancy_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('skills_required', models.TextField(blank=True)),
                ('experience_required', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_vacancies', to='admin_module.department')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('applied_resume', models.FileField(blank=True, null=True, upload_to='applications/resumes/')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('RESUME_REVIEW', 'Resume Under Review'), ('SHORTLISTED', 'Shortlisted'), ('APTITUDE', 'Aptitude Test Scheduled'), ('INTERVIEW', 'Interview Scheduled'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=30)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.jobvacancy')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('candidate', 'vacancy'), name='unique_candidate_vacancy')],
            },
        ),
    ]
