# Generated by Django 6.1 on 2026-09-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, help_text='Application deadline date', null=True),
        ),
    ]
