# Generated by Django 6.0.8 on 2026-09-16 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('hr', '0003_alter_aptitudequestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='aptitude_date',
            field=models.DateField(blank=True, help_text='Scheduled date for aptitude assessment', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='aptitude_remarks',
            field=models.TextField(blank=True, help_text='HR instructions or notes for aptitude round'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='aptitude_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_applications', to='hr.aptitudetest'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='aptitude_time',
            field=models.TimeField(blank=True, help_text='Scheduled time for aptitude assessment', null=True),
        ),
        migrations.CreateModel(
            name='CandidateNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('STATUS_UPDATE', 'Application Status Updated'), ('APTITUDE_SCHEDULED', 'Aptitude Test Scheduled'), ('APTITUDE_RESULT', 'Aptitude Test Result'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_UPDATE', 'Interview Updated'), ('GENERAL', 'General Notification')], default='STATUS_UPDATE', max_length=30)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_notifications', to='candidates.jobapplication')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
