# Generated by Django 6.1 on 2026-09-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('RESUME_REVIEW', 'Resume Under Review'), ('SHORTLISTED', 'Shortlisted'), ('APTITUDE_TEST', 'Aptitude Test'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], db_index=True, default='APPLIED', max_length=25),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPLICATION', 'Application Update'), ('INTERVIEW', 'Interview Schedule'), ('APTITUDE', 'Aptitude Test'), ('GENERAL', 'General Announcement'), ('REGISTRATION', 'Registration')], db_index=True, default='GENERAL', max_length=20),
        ),
    ]
