# Generated by Django 6.1 on 2026-09-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitudetest',
            name='assigned_candidates',
            field=models.ManyToManyField(blank=True, help_text='Candidates specifically assigned to take this assessment', related_name='assigned_tests', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='aptitudetest',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('UPCOMING', 'Upcoming'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', help_text='Current test status (Active, Upcoming, Archived)', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='testresult',
            constraint=models.UniqueConstraint(fields=('candidate', 'test'), name='unique_candidate_test_result'),
        ),
    ]
