# Generated by Django 6.0 on 2026-08-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR Manager'), ('Employee', 'Employee'), ('Candidate', 'Candidate')], default='Admin', max_length=50, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Active', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
