from django.urls import path
from . import views

app_name = "admin_module"

urlpatterns = [
    path("", views.admin_dashboard_view, name="admin_dashboard"),
    path("dashboard/", views.admin_dashboard_view, name="dashboard"),
    path("login/", views.admin_login_view, name="admin_login"),
    path("register/", views.admin_register_view, name="admin_register"),
    path("logout/", views.admin_logout_view, name="admin_logout"),
    path("employees/", views.admin_employees_management_view, name="employees_list"),
    path("employees/add/", views.admin_employee_create_view, name="employee_create"),
    path("employees/<int:employee_id>/", views.admin_employee_profile_view, name="employee_detail"),
    path("employees/<int:employee_id>/edit/", views.admin_employee_edit_view, name="employee_edit"),
    path("employees/<int:employee_id>/delete/", views.admin_employee_delete_view, name="employee_delete"),
    path("hr-managers/", views.admin_hr_managers_management_view, name="hr_managers_list"),
    path("hr-managers/add/", views.admin_hr_manager_create_view, name="hr_manager_create"),
    path("hr-managers/<int:manager_id>/", views.admin_hr_manager_profile_view, name="hr_manager_detail"),
    path("hr-managers/<int:manager_id>/edit/", views.admin_hr_manager_edit_view, name="hr_manager_edit"),
    path("hr-managers/<int:manager_id>/delete/", views.admin_hr_manager_delete_view, name="hr_manager_delete"),
    path("hr-managers/<int:manager_id>/toggle-status/", views.admin_hr_manager_toggle_status_view, name="hr_manager_toggle_status"),
    path("departments/", views.admin_departments_management_view, name="departments_list"),
    path("departments/add/", views.admin_department_create_view, name="department_create"),
    path("departments/<int:department_id>/", views.admin_department_detail_view, name="department_detail"),
    path("departments/<int:department_id>/edit/", views.admin_department_edit_view, name="department_edit"),
    path("departments/<int:department_id>/delete/", views.admin_department_delete_view, name="department_delete"),
    # Announcements Management (Admin CRUD + Publish)
    path("announcements/", views.admin_announcements_management_view, name="announcements_list"),
    path("announcements/add/", views.admin_announcement_create_view, name="announcement_create"),
    path("announcements/<int:announcement_id>/", views.admin_announcement_detail_view, name="announcement_detail"),
    path("announcements/<int:announcement_id>/edit/", views.admin_announcement_edit_view, name="announcement_edit"),
    path("announcements/<int:announcement_id>/delete/", views.admin_announcement_delete_view, name="announcement_delete"),
    path("announcements/<int:announcement_id>/publish/", views.admin_announcement_publish_view, name="announcement_publish"),
    # Recruitment Monitoring (Admin read-only + new employee approvals)
    path("recruitment/", views.admin_recruitment_jobs_view, name="recruitment_list"),
    path("recruitment/jobs/", views.admin_recruitment_jobs_view, name="recruitment_jobs"),
    path("recruitment/status/", views.admin_recruitment_status_view, name="recruitment_status"),
    path("recruitment/status/<int:vacancy_id>/", views.admin_recruitment_job_status_view, name="recruitment_job_status"),
    path("recruitment/selected/", views.admin_recruitment_selected_view, name="recruitment_selected"),
    path("recruitment/candidates/<int:candidate_id>/", views.admin_recruitment_candidate_detail_view, name="recruitment_candidate_detail"),
    path("recruitment/approvals/", views.admin_recruitment_approvals_view, name="recruitment_approvals"),
    path("recruitment/approvals/<int:employee_id>/", views.admin_recruitment_approval_review_view, name="recruitment_approval_review"),
    path("recruitment/approvals/<int:employee_id>/approve/", views.admin_recruitment_approval_approve_view, name="recruitment_approval_approve"),
    # Admin Reports (view & analyze only)
    path("reports/hr-weekly/", views.admin_reports_hr_weekly_view, name="reports_hr_weekly"),
    path("reports/employee-weekly/", views.admin_reports_employee_weekly_view, name="reports_employee_weekly"),
    path("reports/recruitment/", views.admin_reports_recruitment_view, name="reports_recruitment"),
    path("reports/departments/", views.admin_reports_departments_view, name="reports_departments"),
    path("reports/performance/", views.admin_reports_performance_view, name="reports_performance"),
    # Core Modular Navigation Routes matching HRCortex Sidebar
    path("payroll/", views.admin_placeholder_view, {"module_name": "payroll"}, name="payroll_list"),
    path("attendance/", views.admin_placeholder_view, {"module_name": "attendance"}, name="attendance_list"),
    path("performance/", views.admin_placeholder_view, {"module_name": "performance"}, name="performance_list"),
    path("settings/", views.admin_placeholder_view, {"module_name": "settings"}, name="settings_list"),
    # Additional module routes
    path("users/", views.admin_placeholder_view, {"module_name": "users"}, name="users_list"),
    path("job-vacancies/", views.admin_placeholder_view, {"module_name": "job_vacancies"}, name="job_vacancies_list"),
    path("candidates/", views.admin_candidates_management_view, name="candidates_list"),
    path("candidates/add/", views.admin_candidate_create_view, name="candidate_create"),
    path("candidates/<int:candidate_id>/edit/", views.admin_candidate_edit_view, name="candidate_edit"),
    path("candidates/<int:candidate_id>/delete/", views.admin_candidate_delete_view, name="candidate_delete"),
    # Admin Responsibilities (Performance Warnings & HR Recommendations)
    path("responsibilities/warnings/", views.admin_responsibilities_warnings_view, name="admin_responsibilities_warnings"),
    path("responsibilities/warnings/<int:warning_id>/", views.admin_responsibilities_warning_detail_view, name="admin_responsibilities_warning_detail"),
    path("responsibilities/recommendations/", views.admin_responsibilities_recommendations_view, name="admin_responsibilities_recommendations"),
    path("responsibilities/recommendations/<int:warning_id>/review/", views.admin_responsibilities_review_view, name="admin_responsibilities_review"),
    path("responsibilities/recommendations/<int:warning_id>/decision/", views.admin_responsibilities_decision_view, name="admin_responsibilities_decision"),
    path("warnings/", views.admin_responsibilities_warnings_view, name="warnings_list"),
]
